# Generated by Django 6.0.6 on 2026-06-14 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='complexes.complex', verbose_name='complejo')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
                'unique_together': {('complex', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='stock mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='complexes.complex', verbose_name='complejo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='complexes.complex', verbose_name='complejo')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='reservations.reservation', verbose_name='reserva')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='vendido por')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'ítem de venta',
                'verbose_name_plural': 'ítems de venta',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=12, verbose_name='tipo')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('stock_after', models.PositiveIntegerField(verbose_name='stock resultante')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['complex', 'is_active'], name='products_pr_complex_9ac796_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='products_pr_stock_4d23d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['complex', 'created_at'], name='products_sa_complex_b7d2c8_idx'),
        ),
    ]
