# Generated by Django 6.0.6 on 2026-06-14 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='inicio')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No se presentó')], default='PENDING', max_length=12, verbose_name='estado')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada el')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='complexes.court', verbose_name='cancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CARD', 'Tarjeta'), ('MP', 'Mercado Pago')], default='CASH', max_length=12, verbose_name='método')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=12, verbose_name='estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pagado el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='inicio deseado')),
                ('end_time', models.TimeField(verbose_name='fin deseado')),
                ('notified', models.BooleanField(default=False, verbose_name='notificado')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notificado el')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='complexes.court', verbose_name='cancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'lista de espera',
                'verbose_name_plural': 'lista de espera',
                'ordering': ['date', 'start_time', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'date'], name='reservation_court_i_add3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='reservation_user_id_56b0f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('court', 'date', 'start_time'), name='no_double_booking'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['court', 'date', 'notified'], name='reservation_court_i_29051d_idx'),
        ),
    ]
