# Generated by Django 6.0.6 on 2026-06-17 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteComplex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='complexes.complex', verbose_name='complejo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_complexes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'complejo favorito',
                'verbose_name_plural': 'complejos favoritos',
                'ordering': ['order'],
                'unique_together': {('user', 'complex')},
            },
        ),
    ]
