# Generated by Django 6.0.6 on 2026-06-15 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('format', models.CharField(choices=[('SINGLE_ELIM', 'Eliminación simple'), ('DOUBLE_ELIM', 'Eliminación doble'), ('ROUND_ROBIN', 'Round Robin'), ('AMERICANO', 'Americano'), ('MEXICANO', 'Mexicano')], default='ROUND_ROBIN', max_length=12, verbose_name='formato')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Inscripciones abiertas'), ('IN_PROGRESS', 'En curso'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=12, verbose_name='estado')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('max_teams', models.PositiveSmallIntegerField(default=8, verbose_name='máximo de equipos')),
                ('prize_info', models.TextField(blank=True, verbose_name='premios')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='complexes.complex', verbose_name='complejo')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='complexes.sport', verbose_name='deporte')),
            ],
            options={
                'verbose_name': 'torneo',
                'verbose_name_plural': 'torneos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('max_teams', models.PositiveSmallIntegerField(default=8, verbose_name='máximo de equipos')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament', verbose_name='torneo')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('seed', models.PositiveSmallIntegerField(default=0, verbose_name='cabeza de serie')),
                ('players', models.ManyToManyField(blank=True, related_name='tournament_teams', to=settings.AUTH_USER_MODEL, verbose_name='jugadores')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournamentcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['seed', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1, verbose_name='ronda')),
                ('match_number', models.PositiveSmallIntegerField(default=1, verbose_name='número de partido')),
                ('score_a', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntos A')),
                ('score_b', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntos B')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('FINISHED', 'Finalizado'), ('WALKOVER', 'Walkover')], default='PENDING', max_length=12, verbose_name='estado')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='programado para')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='tournaments.team', verbose_name='equipo A')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='tournaments.team', verbose_name='equipo B')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.team', verbose_name='ganador')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['complex', 'status'], name='tournaments_complex_a96650_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['sport'], name='tournaments_sport_i_ff4a84_idx'),
        ),
    ]
