# Generated by Django 6.0.6 on 2026-06-13 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS o nombre de ícono', max_length=60, verbose_name='ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'deporte',
                'verbose_name_plural': 'deportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='complexes/logos/', verbose_name='logo')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='complexes/covers/', verbose_name='portada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido')], default='PENDING', max_length=12, verbose_name='estado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_complexes', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'complejo',
                'verbose_name_plural': 'complejos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplexSport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.complex')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.sport')),
            ],
            options={
                'verbose_name': 'deporte del complejo',
                'verbose_name_plural': 'deportes del complejo',
                'unique_together': {('complex', 'sport')},
            },
        ),
        migrations.AddField(
            model_name='complex',
            name='sports',
            field=models.ManyToManyField(related_name='complexes', through='complexes.ComplexSport', to='complexes.sport', verbose_name='deportes'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('open_time', models.TimeField(verbose_name='apertura')),
                ('close_time', models.TimeField(verbose_name='cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='cerrado')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='complexes.complex', verbose_name='complejo')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['weekday'],
                'unique_together': {('complex', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('surface', models.CharField(blank=True, choices=[('CLAY', 'Tierra'), ('GRASS', 'Césped'), ('SYNTHETIC', 'Sintético'), ('HARD', 'Duro'), ('WOOD', 'Madera'), ('CONCRETE', 'Cemento')], max_length=12, verbose_name='superficie')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio por hora')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='cubierta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='complexes.complex', verbose_name='complejo')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='complexes.sport', verbose_name='deporte')),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'ordering': ['complex', 'sport', 'name'],
                'indexes': [models.Index(fields=['complex', 'is_active'], name='complexes_c_complex_7e7b73_idx'), models.Index(fields=['sport'], name='complexes_c_sport_i_8c8812_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complex',
            index=models.Index(fields=['status'], name='complexes_c_status_581815_idx'),
        ),
        migrations.AddIndex(
            model_name='complex',
            index=models.Index(fields=['slug'], name='complexes_c_slug_fd108b_idx'),
        ),
        migrations.AddIndex(
            model_name='complex',
            index=models.Index(fields=['city'], name='complexes_c_city_5eb55b_idx'),
        ),
    ]
